package com.example.seckill.dao;

import com.example.seckill.dataobject.ItemStockDO;
import com.example.seckill.dataobject.ItemStockDOExample;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import java.util.List;
@Mapper
public interface ItemStockDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_stock
     *
     * @mbg.generated Sun May 01 17:08:56 CST 2022
     */
    long countByExample(ItemStockDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_stock
     *
     * @mbg.generated Sun May 01 17:08:56 CST 2022
     */
    int deleteByExample(ItemStockDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_stock
     *
     * @mbg.generated Sun May 01 17:08:56 CST 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_stock
     *
     * @mbg.generated Sun May 01 17:08:56 CST 2022
     */
    int insert(ItemStockDO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_stock
     *
     * @mbg.generated Sun May 01 17:08:56 CST 2022
     */
    int insertSelective(ItemStockDO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_stock
     *
     * @mbg.generated Sun May 01 17:08:56 CST 2022
     */
    List<ItemStockDO> selectByExample(ItemStockDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_stock
     *
     * @mbg.generated Sun May 01 17:08:56 CST 2022
     */
    ItemStockDO selectByPrimaryKey(Integer id);

    ItemStockDO selectByItemId(Integer itemId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_stock
     *
     * @mbg.generated Sun May 01 17:08:56 CST 2022
     */
    int updateByExampleSelective(@Param("row") ItemStockDO row, @Param("example") ItemStockDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_stock
     *
     * @mbg.generated Sun May 01 17:08:56 CST 2022
     */
    int updateByExample(@Param("row") ItemStockDO row, @Param("example") ItemStockDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_stock
     *
     * @mbg.generated Sun May 01 17:08:56 CST 2022
     */
    int updateByPrimaryKeySelective(ItemStockDO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_stock
     *
     * @mbg.generated Sun May 01 17:08:56 CST 2022
     */
    int updateByPrimaryKey(ItemStockDO row);

    int updateStock(Integer itemId, Integer amount);
}