package com.example.seckill.dataobject;

import lombok.Data;

@Data
public class ItemStockDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item_stock.id
     *
     * @mbg.generated Sun May 01 17:08:56 CST 2022
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item_stock.stock
     *
     * @mbg.generated Sun May 01 17:08:56 CST 2022
     */
    private Integer stock;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item_stock.item_id
     *
     * @mbg.generated Sun May 01 17:08:56 CST 2022
     */
    private Integer itemId;
}